export const dataBox = [
  {
    id: 1,
    title: "HomePage.boxes.box1.title",
    text: "HomePage.boxes.box1.text",
  },
  {
    id: 2,
    title: "HomePage.boxes.box2.title",
    text: "HomePage.boxes.box2.text",
  },
  {
    id: 3,
    title: "HomePage.boxes.box3.title",
    text: "HomePage.boxes.box3.text",
  },
];

export const FAQs = [
  { id: 1, key: "FAQs.Do.Do1" },
  { id: 2, key: "FAQs.Do.Do2" },
  { id: 3, key: "FAQs.Do.Do3" },
  { id: 4, key: "FAQs.Do.Do4" },
  { id: 5, key: "FAQs.Do.Do5" },
  { id: 6, key: "FAQs.Do.Do6" },
  { id: 7, key: "FAQs.Do.Do7" },
  { id: 8, key: "FAQs.Do.Do8" },
  { id: 9, key: "FAQs.Do.Do9" },
  { id: 10, key: "FAQs.Do.Do10" },
  { id: 11, key: "FAQs.Do.Do11" },
  { id: 12, key: "FAQs.Do.Do12" },
  { id: 13, key: "FAQs.Do.Do13" },
  { id: 14, key: "FAQs.Do.Do14" },
  { id: 15, key: "FAQs.Do.Do15" },
  { id: 16, key: "FAQs.Do.Do16" },
  { id: 17, key: "FAQs.Do.Do17" },
  { id: 18, key: "FAQs.Do.Do18" },
  { id: 19, key: "FAQs.Do.Do19" },
  { id: 20, key: "FAQs.Do.Do20" },
  { id: 21, key: "FAQs.Do.Do21" },
  { id: 22, key: "FAQs.Do.Do22" },
  { id: 23, key: "FAQs.Do.Do23" },
  { id: 24, key: "FAQs.Do.Do24" },
  { id: 25, key: "FAQs.Do.Do25" },
  { id: 26, key: "FAQs.Do.Do26" },
  { id: 27, key: "FAQs.Do.Do27" },
  { id: 28, key: "FAQs.Do.Do28" },
  { id: 29, key: "FAQs.Do.Do29" },
  { id: 30, key: "FAQs.Do.Do30" },
  { id: 31, key: "FAQs.Do.Do31" },
  { id: 32, key: "FAQs.Do.Do32" },
  { id: 33, key: "FAQs.Do.Do33" },
  { id: 34, key: "FAQs.Do.Do34" },
  { id: 35, key: "FAQs.Do.Do35" },
  { id: 36, key: "FAQs.Do.Do36" },
];